---
#
- name: evaluate oracle database 11g instance
  stat: path="{{ oracle_database_oracle_home }}/dbs/spfile{{ oracle_database_sid }}.ora"
  become: yes
  become_user: "oracle"
  register: ora_state

- debug:
    var: ora_state

- name: create dbca response file
  template: src=dbca-11g.rsp.j2 dest=/tmp/dbca.rsp
  become: yes
  become_user: "oracle"

- name: create database instance
  command: "{{ oracle_database_oracle_home }}/bin/dbca -silent -responseFile /tmp/dbca.rsp"
  become: yes
  become_user: "oracle"
  args:
    creates: "{{ oracle_database_oracle_home }}/dbs/spfile{{ oracle_database_sid }}.ora"
  register: command_result
  failed_when: "'100% complete' not in command_result.stdout_lines and not ora_state.stat.exists"

- name: generate upstart script
  template: src=templates/oracle-11g.service.j2 dest=/etc/systemd/system/oracle-11g.service
  become: yes
  become_user: "root"
  tags:
    - configure_service

- name: Enable Service
  service: name=oracle-11g enabled=yes
  become: yes
  become_user: "root"
  tags:
    - configure_service

- name: set oracle sid
  lineinfile:
   dest: "/home/oracle/.bash_profile"
   regexp: "^{{ item.start }}"
   line: "{{ item.start }}{{ item.end }}"
   insertbefore: "export PATH"
  become: yes
  become_user: "oracle"
  with_items:
   - { start: "ORACLE_SID=", end: "{{ oracle_database_sid }}" }

- name: add oratab
  template: src=templates/oratab-11g.j2 dest=/etc/oratab owner=oracle group=oinstall
  become: yes
  become_user: "root"
