---
- debug:
    var: oracle_database_release

- name: validate oracle database 11g release is supported
  fail: "msg='{{ oracle_database_release }}release is not valid (supported versions: [11.2.0.4])'"
  when: oracle_database_release is defined and oracle_database_release != '11.2.0.4'

- name: evaluate oracle database 11g 11.2.0.4 installers
  stat: path="files/{{ item.path }}"
  register: zips_state
  with_items: "{{ oracle_database_installers_11_2_0_4 }}"
  when: oracle_database_release == '11.2.0.4'

- name: validation results
  debug:
    var: zips_state

- name: validate installation zips exist
  fail: msg="installation zip file {{ item.item.path }} is not present"
  when: not item.stat.exists or not item.stat.isreg
  with_items: "{{ zips_state.results }}"

- name: validate installation zips checksum
  fail: msg="installation zip file {{ item.item.path }} is not valid"
  when: item.stat.checksum != item.item.checksum
  with_items: "{{ zips_state.results }}"

- name: install the latest version of unzip
  yum: name=unzip state=latest

- name: "unzip installation files"
  unarchive: src="files/{{ item.path }}" dest=/tmp
  when: oracle_database_release == '11.2.0.4'
  with_items: "{{ oracle_database_installers_11_2_0_4 }}"

- name: install pre-installation package
  yum: name=oracle-rdbms-server-11gR2-preinstall
  become: yes
  become_user: "root"

- file:
    path: "{{ item }}"
    state: directory
    owner: "oracle"
    group: "oinstall"
  with_items:
    - "{{ oracle_database_inventory_location }}"
    - "{{ oracle_database_oracle_base }}"
    - "{{ oracle_database_oracle_home }}"
  become: yes
  become_user: "oracle"

- name: preparing database installation template
  template: src=db-install-11g.rsp.j2 dest=/tmp/db-install.rsp
  become: yes
  become_user: "oracle"

- name: update required pre-requisites
  shell: "sed -i -e 's/<RUNLEVEL>/<RUNLEVEL SEVERITY=\"IGNORABLE\">/g' /tmp/database/stage/cvu/cvu_prereq.xml"

- name: run installer
  shell: "/tmp/database/runInstaller -silent -waitforcompletion -ignoreSysPrereqs -responseFile /tmp/db-install.rsp"
  args:
    creates: "{{ oracle_database_oracle_home }}/bin/sqlplus"
  become: yes
  become_user: "oracle"
  register: command_result
  failed_when: "'Successfully Setup Software.' not in command_result.stdout_lines"

- name: installation results
  debug:
    var: command_result

- name: run post-installation scripts as root
  shell: "{{item}}"
  become: yes
  become_user: "root"
  with_items:
    - "{{ oracle_database_inventory_location }}/orainstRoot.sh"
    - "{{ oracle_database_oracle_home }}/root.sh"

- name: set oracle home
  lineinfile:
   dest: "/home/oracle/.bash_profile"
   regexp: "^{{ item.start }}"
   line: "{{ item.start }}{{ item.end }}"
   insertbefore: "export PATH"
  become: yes
  become_user: "oracle"
  with_items:
   - { start: "ORACLE_HOME=", end: "{{ oracle_database_oracle_home }}" }
   - { start: "PATH=$ORACLE_HOME/bin:", end: "$PATH" }
