---
# tasks file for oracle-database
- name: install oracle database
  include: install-db.yml
  become: yes
  become_user: "root"
  tags:
    - install

- name: create listener oracle database 11g
  include: create-listener.yml
  tags:
    - listener

- name: configure instance oracle database 11g
  include: create-instance.yml
  tags:
    - instance
