---
# tasks file for oracle-database
- debug:
    var: oracle_database_version

- name: validate oracle database version is supported
  fail: "msg='version is not valid (supported versions: [11g])'"
  when: oracle_database_version is defined and oracle_database_version != '11g'

- name: install oracle database 11g
  include: install-db-11g.yml
  when: oracle_database_version == '11g'
  tags:
    - install

- name: configure instance oracle database 11g
  include: create-instance-db-11g.yml
  when: oracle_database_version == '11g'
  tags:
    - create-instance

- name: create listener oracle database 11g
  include: create-listener-db-11g.yml
  when: oracle_database_version == '11g'
  tags:
    - create-instance
    - create-listener
